services:
  postgres:
    image: postgres:17-alpine
    container_name: order_processing_postgres
    environment:
      POSTGRES_DB: order_processing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  wso2am:
    image: wso2/wso2am:4.5.0
    container_name: order_processing_wso2
    user: root
    ports:
      - "9443:9443"
      - "8243:8243"
      - "8280:8280"
      - "9763:9763"
    volumes:
      - wso2_data:/home/wso2carbon/wso2am-4.5.0/repository


volumes:
  postgres_data:
  wso2_data:

